---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: api-service
    app.kubernetes.io/part-of: myapp
  name: api
  namespace: project-a
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: api-service
      app.kubernetes.io/part-of: myapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api-service
        app.kubernetes.io/part-of: myapp
    spec:
      containers:
        - image: ghcr.io/rhobs/prometheus-example-app:0.5.1
          imagePullPolicy: IfNotPresent
          name: app
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: api-service
    app.kubernetes.io/part-of: myapp
  name: api
  namespace: project-a
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: web
  selector:
    app.kubernetes.io/name: api-service
    app.kubernetes.io/part-of: myapp
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: api-service
    app.kubernetes.io/part-of: myapp
  name: api
  namespace: project-b
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: api-service
      app.kubernetes.io/part-of: myapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api-service
        app.kubernetes.io/part-of: myapp
    spec:
      containers:
        - image: ghcr.io/rhobs/prometheus-example-app:0.5.1
          imagePullPolicy: IfNotPresent
          name: app
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: api-service
    app.kubernetes.io/part-of: myapp
  name: api
  namespace: project-b
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: web
  selector:
    app.kubernetes.io/name: api-service
    app.kubernetes.io/part-of: myapp
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: myapp
  name: backend
  namespace: project-c
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: backend
      app.kubernetes.io/part-of: myapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: backend
        app.kubernetes.io/part-of: myapp
    spec:
      containers:
        - image: ghcr.io/rhobs/prometheus-example-app:0.5.1
          imagePullPolicy: IfNotPresent
          name: backend
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: myapp
  name: backend
  namespace: project-c
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: web
  selector:
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: myapp
  type: ClusterIP
