apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: perses-webhook-server-cert
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: conversion-webhook
    app.kubernetes.io/name: perses-operator
    app.kubernetes.io/part-of: perses-operator
  name: perses-operator-conversion-webhook
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: perses-operator
    app.kubernetes.io/part-of: observability-operator
status:
  loadBalancer: {}
