---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - perses.dev_perses.yaml
 - perses.dev_persesdashboards.yaml
 - perses.dev_persesdatasources.yaml

commonAnnotations:
  observability.openshift.io/api-support: DevPreview
