---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-stack-operator
  labels:
    app.kubernetes.io/name: monitoring-stack-operator
    app.kubernetes.io/component: operator
    app.kubernetes.io/version: 0.0.1
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: monitoring-stack-operator
      app.kubernetes.io/component: operator
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: monitoring-stack-operator
        app.kubernetes.io/component: operator
        app.kubernetes.io/version: 0.0.1
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: manager
          image: monitoring-stack-operator:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
          resources:
            limits:
              cpu: 200m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 20Mi
      serviceAccountName: monitoring-stack-operator
      terminationGracePeriodSeconds: 30
