apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability-operator
images:
- name: observability-operator
  newName: observability-operator
  newTag: 0.2.0
commonAnnotations:
  package-operator.run/phase: operator
resources:
- ../../operator/
