apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- crds
- perses-operator-deployment.yaml
- perses-operator-cluster-role.yaml
- perses-operator-service-account.yaml
- perses-operator-cluster-role-binding.yaml
- perses-operator-conversion-webhook-service.yaml
- persesdashboard_editor_role.yaml
- persesdashboard_viewer_role.yaml
- persesdatasource_editor_role.yaml
- persesdatasource_viewer_role.yaml
- persesglobaldatasource_editor_role.yaml
- persesglobaldatasource_viewer_role.yaml
- perses-service-account.yaml
