# permissions for end users to view persesglobaldatasources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: persesglobaldatasource-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: perses-operator
    app.kubernetes.io/part-of: perses-operator
  name: persesglobaldatasource-viewer-role
rules:
  - apiGroups:
      - perses.dev
    resources:
      - persesglobaldatasources
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - perses.dev
    resources:
      - persesglobaldatasources/status
    verbs:
      - get
