resources:
- ../crds
- ../dependencies
- ../operator
- ../scorecard
- ../samples

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: observability-operator
  newName: local-registry:30000/observability-operator
  newTag: 0.0.0-ci
