---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitoring-stack-operator-grafana-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monitoring-stack-operator-grafana-operator
subjects:
- kind: ServiceAccount
  name: monitoring-stack-operator-grafana-operator-sa
  namespace: default
