resources:
- observability-operator-deployment.yaml
- observability-operator-service-account.yaml
- observability-operator-cluster-role.yaml
- observability-operator-cluster-role-binding.yaml
- observability-operator-service.yaml
- observability-operator-service-monitor.yaml
- observability-operator-rules.yaml
- monitoring/monitoring-prometheus-rules.yaml
- monitoring/monitoring-alertmanager-rules.yaml
- monitoring/monitoring-prometheus-operator-rules.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: observability-operator
  newTag: 0.0.9
namespace: operators
