resources:
- clusterrolebindings.yaml
- deployment.yaml
- prometheus_operator_clusterrole.yaml
- role.yaml
- serviceaccount.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: monitoring-stack-operator
  newName: monitoring-stack-operator
  newTag: 0.0.3

