resources:
- monitoring-stack-operator-deployment.yaml
- monitoring-stack-operator-service-account.yaml
- monitoring-stack-operator-cluster-role.yaml
- monitoring-stack-operator-cluster-role-binding.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: monitoring-stack-operator
  newTag: 0.0.5
namespace: operators
