apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- observability-operator-deployment.yaml
- observability-operator-service-account.yaml
- observability-operator-cluster-role.yaml
- observability-operator-cluster-role-binding.yaml
- observability-operator-service.yaml

images:
- name: observability-operator
  newName: observability-operator
  newTag: 0.0.29
namespace: operators

patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --images=alertmanager=quay.io/prometheus/alertmanager:v0.26.0
  target:
    group: apps
    kind: Deployment
    version: v1
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --images=prometheus=quay.io/prometheus/prometheus:v2.49.1
  target:
    group: apps
    kind: Deployment
    version: v1
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --images=thanos=quay.io/thanos/thanos:v0.33.0
  target:
    group: apps
    kind: Deployment
    version: v1
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --images=perses=quay.io/persesdev/perses:v0.50.3
  target:
    group: apps
    kind: Deployment
    version: v1
