---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: observability-operator
  labels:
    app.kubernetes.io/name: observability-operator
    app.kubernetes.io/component: operator
    app.kubernetes.io/version: 0.0.1
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: observability-operator
      app.kubernetes.io/component: operator
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: observability-operator
        app.kubernetes.io/component: operator
        app.kubernetes.io/version: 0.0.1
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: operator
          image: observability-operator:0.0.1
          imagePullPolicy: Always
          args:
            - --namespace=$(NAMESPACE)
          env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
          resources:
            limits:
              cpu: 200m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 150Mi
          readinessProbe:
             httpGet:
               path: /healthz
               port: 8081
          livenessProbe:
             httpGet:
               path: /healthz
               port: 8081
          volumeMounts:
          - mountPath: /etc/tls/private
            name: observability-operator-tls
            readOnly: true
      serviceAccountName: observability-operator-sa
      volumes:
      - name: observability-operator-tls
        secret:
          secretName: observability-operator-tls
          optional: true
      terminationGracePeriodSeconds: 30
