---
name: OLM Release

on:
  push:
    branches: [main]
    tags: ["v*"]

jobs:
  release:
    runs-on: ubuntu-latest
    environment: quay

    steps:
      # setup
      - uses: actions/checkout@v2

      - name: Initialize ENV vars
        run: |
          cat $GITHUB_ENV

          echo "GITHUB_REF: $GITHUB_REF"

          SOURCE_NAME=${GITHUB_REF#refs/*/}
          SOURCE_BRANCH=${GITHUB_REF#refs/heads/}
          SOURCE_TAG=${GITHUB_REF#refs/tags/}

          if [[ $SOURCE_NAME == main ]]; then
            VERSION="$(cat VERSION)-$(date +%y%m%d%H%M%S)"
            CHANNELS=development
          else
            VERSION=${SOURCE_NAME##v}
            CHANNELS=development,stable
          fi

          IMG_BASE=$(grep '^IMAGE_TAG_BASE' -- Makefile | cut -f3 -d ' ')

          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "CHANNELS=$CHANNELS" >> $GITHUB_ENV
          echo "IMG=${IMG_BASE}:$VERSION" >> $GITHUB_ENV
          echo "BUNDLE_IMG=${IMG_BASE}-bundle:$VERSION" >> $GITHUB_ENV
          echo "CATALOG_IMG=${IMG_BASE}-catalog:latest" >> $GITHUB_ENV
          echo ---------------------------
          cat $GITHUB_ENV
          echo ---------------------------

      - name: Setup Go environment
        uses: actions/setup-go@v2.1.4
        with:
          go-version: 1.16

      - name: Registry Login
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_LOGIN }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Build Operator Image
        run: make operator-image

      - name: Publish Operator
        run: make operator-push

      - name: Build Bundle Image
        run: make bundle-image

      - name: Publish Bundle
        run: make bundle-push


      - name: Build Catalog Image
        run: |
          env | grep CAT
          make catalog-image

      - name: Publish catalog image
        run: make catalog-push
